[package]
name = "deli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
deli-derive = { version = "0.1.0", path = "../deli-derive" }
idb = "0.2.0"
serde = "1.0.147"
serde-wasm-bindgen = "0.4.5"
serde_json = "1.0.87"
thiserror = "1.0.37"

[dev-dependencies]
gloo-console = "0.2.3"
serde = { version = "1.0.147", features = ["derive"] }
wasm-bindgen-test = "0.3.33"
